"""empty message

Revision ID: 989e8021ea40
Revises: 348a0b4d1b4d
Create Date: 2026-05-14 01:17:38.793002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989e8021ea40'
down_revision = '348a0b4d1b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_room_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'room', ['room_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transcript_room_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'room', ['room_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
        batch_op.alter_column('is_deleted', server_default=None)
        batch_op.add_column(sa.Column('scheduled_deletion', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('scheduled_deletion')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transcript_room_id_fkey'), 'room', ['room_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_room_id_fkey'), 'room', ['room_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('message_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
