"""table rename

Revision ID: e4443aed70ae
Revises: 675a8018aba8
Create Date: 2026-04-20 10:07:51.170862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4443aed70ae'
down_revision = '675a8018aba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_room_code'), ['room_code'], unique=True)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_user_id'), ['user_id'], unique=False)

    op.create_table('room_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rp_user_id', sa.Integer(), nullable=False),
    sa.Column('rp_room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rp_room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['rp_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_participant_rp_room_id'), ['rp_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_participant_rp_user_id'), ['rp_user_id'], unique=False)

    op.create_table('transcript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_room_id'), ['room_id'], unique=False)

    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_created_at'))
        batch_op.drop_index(batch_op.f('ix_transcripts_room_id'))

    op.drop_table('transcripts')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_created_at'))
        batch_op.drop_index(batch_op.f('ix_rooms_owner_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_room_code'))

    op.drop_table('rooms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id'))
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))

    op.drop_table('messages')
    with op.batch_alter_table('room_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_participants_rp_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_participants_rp_user_id'))

    op.drop_table('room_participants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_participants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rp_user_id', sa.INTEGER(), nullable=False),
    sa.Column('rp_room_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['rp_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['rp_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_participants_rp_user_id'), ['rp_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_participants_rp_room_id'), ['rp_room_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('msg_content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('is_blocked', sa.BOOLEAN(), nullable=False),
    sa.Column('failed_login_attempts', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)

    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_code', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_room_code'), ['room_code'], unique=1)
        batch_op.create_index(batch_op.f('ix_rooms_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_created_at'), ['created_at'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ts_content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcripts_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_room_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_created_at'))

    op.drop_table('transcript')
    with op.batch_alter_table('room_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_participant_rp_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_participant_rp_room_id'))

    op.drop_table('room_participant')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_room_id'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    op.drop_table('message')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_room_code'))
        batch_op.drop_index(batch_op.f('ix_room_owner_id'))
        batch_op.drop_index(batch_op.f('ix_room_created_at'))

    op.drop_table('room')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
